# Limpieza y ingeniería de atributos
Este notebook va a ser para limpiar el dataframe.

Se recibe como entrada un dataframe (puede ser el de cualquier año o el consolidado total) y se van a procesar y limpiar las siguientes columnas:

- Género: Poner únicamente los géneros en F, M, No especificado
- Edad: Verificar que no haya edades negativas o que no cuadren (muy bajas o muy altas)
- Fechas: Verificar que estén en formato DD/MM/AAAA
- Eliminar nulos y duplicados

# Bibliotecas

In [2]:
%pip install polars

Collecting polars
  Downloading polars-1.35.2-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.35.2 (from polars)
  Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl.metadata (1.5 kB)
Downloading polars-1.35.2-py3-none-any.whl (783 kB)
   ---------------------------------------- 0.0/783.6 kB ? eta -:--:--
   ---------------------------------------- 783.6/783.6 kB 8.4 MB/s eta 0:00:00
Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   -- ------------------------------------- 2.4/41.3 MB 11.7 MB/s eta 0:00:04
   ---- ----------------------------------- 4.7/41.3 MB 11.3 MB/s eta 0:00:04
   ------ --------------------------------- 6.6/41.3 MB 10.9 MB/s eta 0:00:04
   -------- ------------------------------- 8.7/41.3 MB 10.6 MB/s eta 0:00:04
   ---------- ----------------------------- 10.7/41.3 MB 10.5 MB/s eta 0:00:03
   ------------ --------------------------- 12.8/41.3 MB 10.3 MB/s eta 0:00:03
   -------------- ------------------------- 14.9/41.3 MB 10.3 MB/s eta 0:00:03
   ---------------- ----------------------- 17.0/41.3 MB 10.3 MB/s eta 0:00:03
   ------------------ --------------------- 18.6/41.3 MB 10.1 MB/s eta 0:00:03
   ------------------- -------------------- 20.2/41.3 MB 9.8 MB/s eta 0:00:03
   --------------------- ------------------ 21.8/41.3 MB 9.6 MB/s eta 0:00:03
   ---------------------- ----------------- 23.3/41.3 MB 9.5 MB/s eta 0:00:02
   ----------------------- ---------------- 24.6/41.3 MB 9.2 MB/s eta 0:00:02
   ------------------------- -------------- 26.0/41.3 MB 9.0 MB/s eta 0:00:02
   -------------------------- ------------- 27.3/41.3 MB 8.8 MB/s eta 0:00:02
   --------------------------- ------------ 28.6/41.3 MB 8.6 MB/s eta 0:00:02
   ---------------------------- ----------- 29.6/41.3 MB 8.5 MB/s eta 0:00:02
   ----------------------------- ---------- 30.4/41.3 MB 8.1 MB/s eta 0:00:02
   ----------------------------- ---------- 30.9/41.3 MB 7.9 MB/s eta 0:00:02
   ------------------------------ --------- 31.7/41.3 MB 7.7 MB/s eta 0:00:02
   ------------------------------- -------- 32.5/41.3 MB 7.4 MB/s eta 0:00:02
   -------------------------------- ------- 33.3/41.3 MB 7.3 MB/s eta 0:00:02
   -------------------------------- ------- 33.8/41.3 MB 7.1 MB/s eta 0:00:02
   --------------------------------- ------ 34.6/41.3 MB 6.9 MB/s eta 0:00:01
   ---------------------------------- ----- 35.1/41.3 MB 6.7 MB/s eta 0:00:01
   ---------------------------------- ----- 35.7/41.3 MB 6.6 MB/s eta 0:00:01
   ----------------------------------- ---- 36.4/41.3 MB 6.5 MB/s eta 0:00:01
   ------------------------------------ --- 37.2/41.3 MB 6.3 MB/s eta 0:00:01
   ------------------------------------ --- 37.7/41.3 MB 6.3 MB/s eta 0:00:01
   ------------------------------------- -- 38.5/41.3 MB 6.1 MB/s eta 0:00:01
   ------------------------------------- -- 39.1/41.3 MB 6.0 MB/s eta 0:00:01
   -------------------------------------- - 39.6/41.3 MB 5.9 MB/s eta 0:00:01
   -------------------------------------- - 40.1/41.3 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.3 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  41.2/41.3 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 5.6 MB/s eta 0:00:00
Installing collected packages: polars-runtime-32, polars
Successfully installed polars-1.35.2 polars-runtime-32-1.35.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import polars as pl
import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import re
from collections import Counter

# Obtenemos los datos de entrada

In [24]:
df = pl.read_parquet("DATA/consolidado_2017.parquet")
df

shape: (9_498_044, 10)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici  ┆ Ciclo_Esta ┆ … ┆ Ciclo_Est ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---   ┆ cion_Retir ┆   ┆ acion_Arr ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str   ┆ o          ┆   ┆ ibo       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆       ┆ ---        ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│            ┆            ┆       ┆ str        ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 42         ┆ 1570  ┆ 33         ┆ … ┆ 1         ┆ 01/01/201 ┆ 0:16:49   ┆ 2017/1.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 36         ┆ 7083  ┆ 27         ┆ … ┆ 123       ┆ 01/01/201 ┆ 0:18:28   ┆ 2017/1.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 18         ┆ 4093  ┆ 157        ┆ … ┆ 157       ┆ 01/01/201 ┆ 1:05:31   ┆ 2017/1.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 20         ┆ 7704  ┆ 87         ┆ … ┆ 43        ┆ 01/01/201 ┆ 0:18:27   ┆ 2017/1.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 34         ┆ 7176  ┆ 47         ┆ … ┆ 123       ┆ 01/01/201 ┆ 0:26:08   ┆ 2017/1.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ …          ┆ …          ┆ …     ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ M          ┆ 25         ┆ 10504 ┆ 326        ┆ … ┆ 148       ┆ 30/09/201 ┆ 0:22:37   ┆ 2017/9.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 32         ┆ 4367  ┆ 329        ┆ … ┆ 393       ┆ 30/09/201 ┆ 0:16:30   ┆ 2017/9.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 38         ┆ 9543  ┆ 64         ┆ … ┆ 74        ┆ 30/09/201 ┆ 0:03:57   ┆ 2017/9.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 24         ┆ 10120 ┆ 129        ┆ … ┆ 42        ┆ 30/09/201 ┆ 0:09:44   ┆ 2017/9.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
│ M          ┆ 33         ┆ 3853  ┆ 32         ┆ … ┆ 56        ┆ 30/09/201 ┆ 0:05:45   ┆ 2017/9.cs │
│            ┆            ┆       ┆            ┆   ┆           ┆ 7         ┆           ┆ v         │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Eliminamos nulos y duplicados

In [14]:
# Verificar cuántos nulos hay
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
# Rellenar con "No especificado" todos los nulos existentes
df = df.fill_null("No especificado")

In [5]:
# Verificamos que ya no haya nulos
df.null_count()

shape: (1, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ u32  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆      ┆ ---        ┆   ┆ ---        ┆ u32       ┆ u32       ┆ u32       │
│            ┆            ┆      ┆ u32        ┆   ┆ u32        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0    ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
# Ver cuántos duplicados hay
df.is_duplicated().sum()

0

In [7]:
#Para eliminar duplicados
df.unique()

shape: (9_069_543, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆      ┆ ---        ┆   ┆ ---        ┆ str       ┆ str       ┆ str       │
│            ┆            ┆      ┆ str        ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 26         ┆ 6546 ┆ 27         ┆ … ┆ 4          ┆ 2016-01-2 ┆ 15:35:58. ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 2         ┆ 157000    ┆ v         │
│ F          ┆ 33         ┆ 5186 ┆ 89         ┆ … ┆ 101        ┆ 2016-02-1 ┆ 13:13:28  ┆ 2016/2.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ F          ┆ 18         ┆ 3476 ┆ 130        ┆ … ┆ 141        ┆ 2016-05-1 ┆ 18:41:33. ┆ 2016/5.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆ 607000    ┆ v         │
│ F          ┆ 56         ┆ 5320 ┆ 76         ┆ … ┆ 156        ┆ 2016-01-1 ┆ 10:35:25  ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 2         ┆           ┆ v         │
│ M          ┆ 35         ┆ 2962 ┆ 63         ┆ … ┆ 289        ┆ 26/08/201 ┆ 23:49:51  ┆ 2016/8.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ F          ┆ 29         ┆ 6072 ┆ 182        ┆ … ┆ 80         ┆ 2016-04-0 ┆ 10:57:56. ┆ 2016/4.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 9         ┆ 843000    ┆ v         │
│ M          ┆ 29         ┆ 2196 ┆ 329        ┆ … ┆ 325        ┆ 19/10/201 ┆ 19:27:04  ┆ 2016/10.c │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ sv        │
│ F          ┆ 24         ┆ 6162 ┆ 158        ┆ … ┆ 135        ┆ 2016-03-2 ┆ 19:27:46  ┆ 2016/3.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 9         ┆           ┆ v         │
│ M          ┆ 40         ┆ 1522 ┆ 41         ┆ … ┆ 265        ┆ 06/08/201 ┆ 16:25:25  ┆ 2016/8.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
│ F          ┆ 32         ┆ 4639 ┆ 27         ┆ … ┆ 124        ┆ 05/08/201 ┆ 12:57:00  ┆ 2016/8.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6         ┆           ┆ v         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [8]:
# Ver cuántos duplicados hay
df.is_duplicated().sum()

0

# Tratamiento a columna "Genero_Usuario"
Solo vamos a tomar en cuenta los registros que sean 'F', 'M' y 'No especificado'. Los registros que no sean 'F' o 'M', serán reemplazados por 'No especificado'.

Estos registros ya son conocidos, son los valores: 'O', '?' y 'nan'

In [15]:
valores_no_estandar = ['O', '?', 'nan'] 
df = df.with_columns(
    pl.col("Genero_Usuario").replace(valores_no_estandar, 'No especificado')
)

print("\nValores de 'Genero_Usuario' después de la limpieza:")
print(df['Genero_Usuario'].value_counts())

Valores de 'Genero_Usuario' después de la limpieza:
shape: (2, 2)
┌────────────────┬─────────┐
│ Genero_Usuario ┆ count   │
│ ---            ┆ ---     │
│ str            ┆ u32     │
╞════════════════╪═════════╡
│ M              ┆ 6810462 │
│ F              ┆ 2259081 │
└────────────────┴─────────┘

# Tratamiento a columnas de fechas

In [ ]:
#Revisar si podemos estandarizar los años con horas extrañas, sino, solo trabajamos desde 2017
df = df.with_columns(
    pl.col("Fecha_Retiro")
      .cast(pl.Utf8)
      .str.replace("-", "/")
      .str.strptime(pl.Date, format="%d/%m/%Y", strict=False),

    pl.col("Fecha_Arribo")
      .cast(pl.Utf8)
      .str.replace("-", "/")
      .str.strptime(pl.Date, format="%d/%m/%Y", strict=False)
)

print("2010 procesado correctamente")

2010 procesado correctamente

In [ ]:
#Revisar si podemos estandarizar los años con horas extrañas, sino, solo trabajamos desde 2017
def fix_time(col):
    return (
        pl.col(col)
        # Si falta microsegundos: agregar ".000000"
        .str.replace_all(r"^(\d{1,2}:\d{2}:\d{2})$", r"\1.000000")
        # Si la hora tiene un solo dígito al inicio: anteponer "0"
        .str.replace_all(r"^(\d:)", r"0\1")
        # Convertir a time
        .str.strptime(pl.Time, format="%H:%M:%S%.f", strict=False)
    )

df = df.with_columns(
    [
        fix_time("Hora_Retiro").alias("Hora_Retiro"),
        fix_time("Hora_Arribo").alias("Hora_Arribo"),
    ]
)

df

shape: (9_069_543, 10)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Genero_Usu ┆ Edad_Usuar ┆ Bici ┆ Ciclo_Esta ┆ … ┆ Ciclo_Esta ┆ Fecha_Arr ┆ Hora_Arri ┆ _source_f │
│ ario       ┆ io         ┆ ---  ┆ cion_Retir ┆   ┆ cion_Arrib ┆ ibo       ┆ bo        ┆ ile       │
│ ---        ┆ ---        ┆ str  ┆ o          ┆   ┆ o          ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆      ┆ ---        ┆   ┆ ---        ┆ date      ┆ time      ┆ str       │
│            ┆            ┆      ┆ str        ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ M          ┆ 51         ┆ 5558 ┆ 74         ┆ … ┆ 80         ┆ null      ┆ null      ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ v         │
│ F          ┆ 34         ┆ 4760 ┆ 123        ┆ … ┆ 30         ┆ null      ┆ 00:11:07. ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆ 463       ┆ v         │
│ M          ┆ 29         ┆ 1599 ┆ 91         ┆ … ┆ 29         ┆ null      ┆ null      ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ v         │
│ M          ┆ 25         ┆ 5840 ┆ 138        ┆ … ┆ 155        ┆ null      ┆ null      ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ v         │
│ M          ┆ 24         ┆ 1532 ┆ 29         ┆ … ┆ 11         ┆ null      ┆ null      ┆ 2016/1.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ v         │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ M          ┆ 45         ┆ 3834 ┆ 88         ┆ … ┆ 260        ┆ 2016-09-3 ┆ null      ┆ 2016/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆           ┆ v         │
│ F          ┆ 24         ┆ 7157 ┆ 303        ┆ … ┆ 303        ┆ 2016-09-3 ┆ null      ┆ 2016/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆           ┆ v         │
│ M          ┆ 27         ┆ 6817 ┆ 27         ┆ … ┆ 1          ┆ 2016-09-3 ┆ null      ┆ 2016/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆           ┆ v         │
│ F          ┆ 27         ┆ 2570 ┆ 107        ┆ … ┆ 195        ┆ 2016-09-3 ┆ null      ┆ 2016/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆           ┆ v         │
│ M          ┆ 28         ┆ 4998 ┆ 101        ┆ … ┆ 266        ┆ 2016-09-3 ┆ null      ┆ 2016/9.cs │
│            ┆            ┆      ┆            ┆   ┆            ┆ 0         ┆           ┆ v         │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘